#!/usr/bin/env node
/**
 * Generates every consumer of the two source files:
 *   design/icons/icons.json      → svg/<name>.svg, sprite.svg, gallery.html,
 *                                  mobile/src/components/icons.gen.ts
 *   design/anatomy/muscles.json  → ../anatomy/body-front.svg, body-back.svg,
 *                                  mobile/src/components/bodyMap.gen.ts
 *
 * Edit the JSON, run `node design/icons/build.mjs`, never edit the outputs.
 */
import { readFileSync, writeFileSync, mkdirSync, rmSync, readdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const repo = join(here, '..', '..');
const icons = JSON.parse(readFileSync(join(here, 'icons.json'), 'utf8'));
const body = JSON.parse(readFileSync(join(repo, 'design/anatomy/muscles.json'), 'utf8'));

const { grid, stroke, linecap, linejoin } = icons.meta;
const names = Object.keys(icons.icons);

// ---------------------------------------------------------------- icons ----
const paths = (icon) =>
  [
    ...(icon.d ?? []).map((d) => `<path d="${d}"/>`),
    ...(icon.f ?? []).map((d) => `<path d="${d}" fill="currentColor" stroke="none"/>`),
  ].join('');

const svgAttrs = `fill="none" stroke="currentColor" stroke-width="${stroke}" stroke-linecap="${linecap}" stroke-linejoin="${linejoin}"`;

const svgDir = join(here, 'svg');
rmSync(svgDir, { recursive: true, force: true });
mkdirSync(svgDir, { recursive: true });
for (const [name, icon] of Object.entries(icons.icons)) {
  writeFileSync(
    join(svgDir, `${name}.svg`),
    `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${grid} ${grid}" width="${grid}" height="${grid}" ${svgAttrs}>${paths(icon)}</svg>\n`,
  );
}

writeFileSync(
  join(here, 'sprite.svg'),
  `<svg xmlns="http://www.w3.org/2000/svg" width="0" height="0" style="position:absolute">\n<defs>\n` +
    names
      .map(
        (n) =>
          `  <symbol id="i-${n}" viewBox="0 0 ${grid} ${grid}" ${svgAttrs}>${paths(icons.icons[n])}</symbol>`,
      )
      .join('\n') +
    `\n</defs>\n</svg>\n`,
);

// -------------------------------------------------------------- anatomy ----
const MIRROR = `matrix(-1 0 0 1 ${body.meta.mirrorAxis * 2} 0)`;

const shapeEl = (s, extra = '') => {
  if (s.p) return `<path d="${s.p}"${extra}/>`;
  if (s.e) return `<ellipse cx="${s.e[0]}" cy="${s.e[1]}" rx="${s.e[2]}" ry="${s.e[3]}"${extra}/>`;
  if (s.r)
    return `<rect x="${s.r[0]}" y="${s.r[1]}" width="${s.r[2]}" height="${s.r[3]}" rx="${s.r[4] ?? 0}"${extra}/>`;
  throw new Error(`unknown shape: ${JSON.stringify(s)}`);
};

/** A shape, plus its reflection when the shape is lateral. */
const withMirror = (el, mirror) => (mirror ? `${el}<g transform="${MIRROR}">${el}</g>` : el);

const groupShapes = (g) => g.shapes.map((sh) => withMirror(shapeEl(sh), g.mirror)).join('');

function bodySvg(view) {
  const sil = body.silhouette[view]
    .map((s) => withMirror(shapeEl(s), s.mirror))
    .join('');
  const groups = Object.entries(body[view])
    .map(([key, g]) => `  <g id="m-${key}" class="muscle" data-muscle="${key}">${groupShapes(g)}</g>`)
    .join('\n');
  return (
    `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${body.meta.viewBox}" width="132" height="300">\n` +
    `<style>\n` +
    `  .silhouette{fill:#E2E3E7;stroke:#2C3040;stroke-width:${body.meta.outlineWidth};stroke-linejoin:round}\n` +
    `  .muscle{fill:#C2C5CC;stroke:#2C3040;stroke-width:${body.meta.muscleWidth};stroke-linejoin:round}\n` +
    `  .muscle.primary{fill:#FB2C36}\n` +
    `  .muscle.secondary{fill:#FB2C36;opacity:.45}\n` +
    `  @media (prefers-color-scheme:dark){\n` +
    `    .silhouette{fill:#2A2D34;stroke:#0A0B0D}\n` +
    `    .muscle{fill:#3E424B;stroke:#0A0B0D}\n` +
    `    .muscle.primary{fill:#FF3B47}\n` +
    `    .muscle.secondary{fill:#FF3B47}\n` +
    `  }\n` +
    `</style>\n` +
    `  <g class="silhouette">${sil}</g>\n${groups}\n</svg>\n`
  );
}

writeFileSync(join(repo, 'design/anatomy/body-front.svg'), bodySvg('front'));
writeFileSync(join(repo, 'design/anatomy/body-back.svg'), bodySvg('back'));

// ------------------------------------------------------- generated TS ------
const ts = (o) => JSON.stringify(o, null, 2).replace(/"([A-Za-z_$][\w$]*)":/g, '$1:');
const banner = '// Generated by design/icons/build.mjs — do not edit by hand.\n';

writeFileSync(
  join(repo, 'mobile/src/components/icons.gen.ts'),
  banner +
    `\nexport const ICON_GRID = ${grid};\n` +
    `export const ICON_STROKE = ${stroke};\n\n` +
    `export type IconName =\n${names.map((n) => `  | '${n}'`).join('\n')};\n\n` +
    `export const ICONS: Record<IconName, { d?: string[]; f?: string[] }> = ${ts(
      Object.fromEntries(names.map((n) => [n, { d: icons.icons[n].d, f: icons.icons[n].f }])),
    )};\n`,
);

const muscleKeys = [...new Set([...Object.keys(body.front), ...Object.keys(body.back)])];
writeFileSync(
  join(repo, 'mobile/src/components/bodyMap.gen.ts'),
  banner +
    `\nexport type BodyView = 'front' | 'back';\n` +
    `export type MuscleKey =\n${muscleKeys.map((k) => `  | '${k}'`).join('\n')};\n\n` +
    `export type BodyShape = { p?: string; e?: number[]; r?: number[]; mirror?: boolean };\n\n` +
    `export const BODY_VIEW_BOX = '${body.meta.viewBox}';\n` +
    `export const BODY_MIRROR = '${MIRROR}';\n\n` +
    `export const BODY_OUTLINE_WIDTH = ${body.meta.outlineWidth};\n` +
    `export const BODY_MUSCLE_WIDTH = ${body.meta.muscleWidth};\n\n` +
    `export const SILHOUETTE: Record<BodyView, BodyShape[]> = ${ts(body.silhouette)};\n\n` +
    `export const MUSCLES: Record<BodyView, Partial<Record<MuscleKey, { mirror: boolean; shapes: BodyShape[] }>>> = ${ts(
      { front: body.front, back: body.back },
    )};\n\n` +
    `export const SPLITS: Record<string, { primary: MuscleKey[]; secondary: MuscleKey[] }> = ${ts(
      body.splits,
    )};\n`,
);

// -------------------------------------------------------------- gallery ----
const byCat = {};
for (const [name, icon] of Object.entries(icons.icons)) (byCat[icon.cat] ??= []).push(name);

const iconCard = (n) =>
  `<figure class="ic"><svg viewBox="0 0 ${grid} ${grid}" ${svgAttrs}>${paths(icons.icons[n])}</svg><figcaption>${n}</figcaption></figure>`;

const bodySvg2 = (v, on = new Set(), semi = new Set(), titles = false) => {
  const sil = body.silhouette[v].map((x) => withMirror(shapeEl(x), x.mirror)).join('');
  const groups = Object.entries(body[v])
    .map(([key, g]) => {
      const cls = on.has(key) ? 'muscle primary' : semi.has(key) ? 'muscle secondary' : 'muscle';
      return `<g class="${cls}" data-muscle="${key}">${titles ? `<title>${key}</title>` : ''}${groupShapes(g)}</g>`;
    })
    .join('');
  return `<svg viewBox="${body.meta.viewBox}"><g class="silhouette">${sil}</g>${groups}</svg>`;
};

const splitCard = ([name, s]) =>
  `<figure class="body"><div class="pair">${bodySvg2('front', new Set(s.primary), new Set(s.secondary))}${bodySvg2(
    'back',
    new Set(s.primary),
    new Set(s.secondary),
  )}</div><figcaption>${name}<span>${s.primary.join(' · ')}</span></figcaption></figure>`;

const anatomyCard = (view) =>
  `<figure class="body big">${bodySvg2(view, new Set(), new Set(), true)}<figcaption>${view}<span>hover a muscle</span></figcaption></figure>`;

const DARK_TOKENS =
  '--bg:#0C0D10;--card:rgba(255,255,255,.05);--line:rgba(255,255,255,.09);--tp:#F2F3F5;--ts:#A3A8B0;--tm:#787E86;--ink:#F4F5F7;--red:#FF3B47;--sil:#2A2D34;--mus:#3E424B;--out:#0A0B0D';

const GALLERY_HEAD = `<title>Icon &amp; Anatomy Library</title>
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap">
<style>
:root{--bg:#EAEAEC;--card:rgba(255,255,255,.62);--line:rgba(20,20,25,.08);--tp:#1A1B1E;--ts:#6C6F76;--tm:#8C9098;--ink:#16171A;--red:#FB2C36;--sil:#E2E3E7;--mus:#C2C5CC;--out:#2C3040}
@media (prefers-color-scheme:dark){:root:not([data-theme="light"]){${DARK_TOKENS}}}
:root[data-theme="dark"]{${DARK_TOKENS}}
*{box-sizing:border-box;margin:0}
body{background:var(--bg);color:var(--tp);font:15px/1.5 Inter,system-ui,sans-serif;padding:40px 24px 80px}
.wrap{max-width:1100px;margin:0 auto}
h1{font-size:28px;font-weight:700;letter-spacing:-.02em}
h2{font-size:13px;font-weight:600;letter-spacing:.1em;text-transform:uppercase;color:var(--tm);margin:38px 0 14px}
p.lede{color:var(--ts);margin-top:8px;max-width:64ch}
code{font-size:13px;background:var(--card);border:1px solid var(--line);border-radius:5px;padding:1px 5px}
.grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(104px,1fr));gap:10px}
.ic{background:var(--card);border:1px solid var(--line);border-radius:14px;padding:14px 8px 10px;display:flex;flex-direction:column;align-items:center;gap:9px}
.ic svg{width:26px;height:26px;color:var(--ink)}
.ic figcaption{font-size:10.5px;color:var(--tm);text-align:center;word-break:break-word}
.bodies{display:grid;grid-template-columns:repeat(auto-fill,minmax(180px,1fr));gap:14px}
.body{background:var(--card);border:1px solid var(--line);border-radius:16px;padding:14px;display:flex;flex-direction:column;align-items:center;gap:8px}
.body svg{width:100%;max-width:130px;height:auto}
.body.big svg{max-width:210px}
.pair{display:flex;gap:8px;width:100%;justify-content:center}
.pair svg{max-width:none;flex:1}
.body figcaption{font-size:12px;font-weight:500;text-align:center}
.body figcaption span{display:block;font-size:10.5px;color:var(--tm);font-weight:400}
.silhouette{fill:var(--sil);stroke:var(--out);stroke-width:${body.meta.outlineWidth};stroke-linejoin:round}
.muscle{fill:var(--mus);stroke:var(--out);stroke-width:${body.meta.muscleWidth};stroke-linejoin:round;transition:fill .15s}
.muscle.primary{fill:var(--red)}
.muscle.secondary{fill:var(--red);opacity:.45}
.big .muscle:hover{fill:var(--red)}
</style>`;

const GALLERY_BODY = `<div class="wrap">
<h1>Icon &amp; anatomy library</h1>
<p class="lede">${names.length} icons on a ${grid}px grid, ${stroke} stroke, round caps — and two anatomical bodies with ${muscleKeys.length} addressable muscle groups. Generated from <code>design/icons/icons.json</code> and <code>design/anatomy/muscles.json</code>.</p>
${Object.entries(byCat)
  .map(
    ([cat, list]) =>
      `<h2>${icons.categories[cat] ?? cat} · ${list.length}</h2><div class="grid">${list.map(iconCard).join('')}</div>`,
  )
  .join('\n')}
<h2>Anatomy · ${muscleKeys.length} groups</h2>
<div class="bodies">${anatomyCard('front')}${anatomyCard('back')}</div>
<h2>Split maps · ${Object.keys(body.splits).length}</h2>
<div class="bodies">${Object.entries(body.splits).map(splitCard).join('')}</div>
</div>`;

writeFileSync(
  join(here, 'gallery.html'),
  `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">\n${GALLERY_HEAD}</head><body>${GALLERY_BODY}</body></html>\n`,
);
// the same page as a fragment, for publishing as an Artifact (which supplies
// the document skeleton itself)
writeFileSync(join(here, 'gallery.artifact.html'), `${GALLERY_HEAD}\n${GALLERY_BODY}\n`);

console.log(
  `icons: ${names.length} svg files + sprite · anatomy: ${muscleKeys.length} groups × 2 views · ` +
    `generated ${readdirSync(svgDir).length} files in design/icons/svg/`,
);
