// Generated by design/icons/build.mjs — do not edit by hand.

export type BodyView = 'front' | 'back';
export type MuscleKey =
  | 'traps'
  | 'shoulders'
  | 'chest'
  | 'biceps'
  | 'forearms'
  | 'core'
  | 'quads'
  | 'calves'
  | 'back'
  | 'triceps'
  | 'glutes'
  | 'hamstrings';

export type BodyShape = { p?: string; e?: number[]; r?: number[]; mirror?: boolean };

export const BODY_VIEW_BOX = '0 0 240 520';
export const BODY_MIRROR = 'matrix(-1 0 0 1 240 0)';

export const BODY_OUTLINE_WIDTH = 3.2;
export const BODY_MUSCLE_WIDTH = 2.4;

export const SILHOUETTE: Record<BodyView, BodyShape[]> = {
  front: [
    {
      e: [
        120,
        46,
        25,
        31
      ]
    },
    {
      p: "M104 68h32v20c0 7-7 12-16 12s-16-5-16-12z"
    },
    {
      p: "M120 86c-20 0-42 6-54 18-12 12-14 32-10 54 4 22 12 40 18 58 6 16 10 34 12 52 2 12 6 22 14 28 8 6 14 8 20 10 6-2 12-4 20-10 8-6 12-16 14-28 2-18 6-36 12-52 6-18 14-36 18-58 4-22 2-42-10-54-12-12-34-18-54-18z"
    },
    {
      p: "M68 110c-11 8-18 27-21 50-3 21-3 39 0 51 3 12 18 13 22 2 6-19 11-45 13-70 2-20 0-32-4-36-3-3-7-1-10 3z",
      mirror: true
    },
    {
      p: "M56 214c-10 13-16 35-18 58-2 17-1 29 3 35 4 7 15 5 17-5 4-21 8-47 9-69 1-12-2-20-6-22-2-1-4 1-5 3z",
      mirror: true
    },
    {
      e: [
        47,
        334,
        13,
        20
      ],
      mirror: true
    },
    {
      p: "M114 282c-21 0-34 13-38 33-4 21-2 47 4 67 4 15 11 23 17 25 6 2 12-2 13-10 3-27 4-75 3-100 0-9-1-15-2-15z",
      mirror: true
    },
    {
      p: "M112 386c-15 4-22 24-23 48-1 21 2 39 6 51 3 9 16 9 18-1 3-23 4-74 1-94 0-3-1-4-2-4z",
      mirror: true
    },
    {
      r: [
        88,
        488,
        34,
        17,
        8
      ],
      mirror: true
    }
  ],
  back: [
    {
      e: [
        120,
        46,
        25,
        31
      ]
    },
    {
      p: "M104 68h32v20c0 7-7 12-16 12s-16-5-16-12z"
    },
    {
      p: "M120 86c-20 0-42 6-54 18-12 12-14 32-10 54 4 22 12 40 18 58 6 16 10 34 12 52 2 12 6 22 14 28 8 6 14 8 20 10 6-2 12-4 20-10 8-6 12-16 14-28 2-18 6-36 12-52 6-18 14-36 18-58 4-22 2-42-10-54-12-12-34-18-54-18z"
    },
    {
      p: "M68 110c-11 8-18 27-21 50-3 21-3 39 0 51 3 12 18 13 22 2 6-19 11-45 13-70 2-20 0-32-4-36-3-3-7-1-10 3z",
      mirror: true
    },
    {
      p: "M56 214c-10 13-16 35-18 58-2 17-1 29 3 35 4 7 15 5 17-5 4-21 8-47 9-69 1-12-2-20-6-22-2-1-4 1-5 3z",
      mirror: true
    },
    {
      e: [
        47,
        334,
        13,
        20
      ],
      mirror: true
    },
    {
      p: "M114 282c-21 0-34 13-38 33-4 21-2 47 4 67 4 15 11 23 17 25 6 2 12-2 13-10 3-27 4-75 3-100 0-9-1-15-2-15z",
      mirror: true
    },
    {
      p: "M112 386c-15 4-22 24-23 48-1 21 2 39 6 51 3 9 16 9 18-1 3-23 4-74 1-94 0-3-1-4-2-4z",
      mirror: true
    },
    {
      r: [
        88,
        488,
        34,
        17,
        8
      ],
      mirror: true
    }
  ]
};

export const MUSCLES: Record<BodyView, Partial<Record<MuscleKey, { mirror: boolean; shapes: BodyShape[] }>>> = {
  front: {
    traps: {
      mirror: true,
      shapes: [
        {
          p: "M116 84c-12 2-24 8-34 18 10 8 22 12 34 12z"
        },
        {
          p: "M112 70c-1 10-4 19-9 27 6 3 12 1 15-4l1-23z"
        }
      ]
    },
    shoulders: {
      mirror: true,
      shapes: [
        {
          p: "M80 100c-14 8-22 26-22 46 0 11 7 15 15 8 8-6 14-22 16-38 1-10-3-18-9-16z"
        },
        {
          p: "M92 100c-9 6-14 18-14 31 0 9 6 11 12 5 7-6 10-20 10-29 0-6-4-9-8-7z"
        }
      ]
    },
    chest: {
      mirror: true,
      shapes: [
        {
          p: "M117 112c-15 0-29 4-36 13-7 10-5 27 4 35 11 10 27 8 32 0 2-14 2-36 0-48z"
        },
        {
          p: "M117 100c-13 0-26 2-34 8 8 5 21 8 34 8z"
        }
      ]
    },
    biceps: {
      mirror: true,
      shapes: [
        {
          p: "M74 156c-11 6-17 24-17 43 0 13 7 19 15 12 8-8 12-28 12-45 0-9-4-14-10-10z"
        },
        {
          p: "M88 160c-3 12-5 26-5 38 5-1 8-8 9-18 1-11 0-19-4-20z"
        }
      ]
    },
    forearms: {
      mirror: true,
      shapes: [
        {
          p: "M62 214c-11 12-17 34-19 57-1 14 4 20 10 14 8-10 14-34 16-55 1-11-2-20-7-16z"
        },
        {
          p: "M74 224c-3 20-7 42-11 60 6 1 10-6 12-18 3-18 4-34 2-42z"
        }
      ]
    },
    core: {
      mirror: true,
      shapes: [
        {
          r: [
            101,
            166,
            17,
            22,
            6
          ]
        },
        {
          r: [
            101,
            192,
            17,
            22,
            6
          ]
        },
        {
          r: [
            101,
            218,
            17,
            22,
            6
          ]
        },
        {
          r: [
            101,
            244,
            17,
            26,
            7
          ]
        },
        {
          p: "M86 164c4 3 8 5 12 6l-2 11c-5-1-9-3-13-6z"
        },
        {
          p: "M86 182c4 3 8 5 12 6l-2 11c-5-1-9-3-13-6z"
        },
        {
          p: "M87 200c4 3 8 5 12 6l-2 11c-5-1-9-3-13-6z"
        },
        {
          p: "M84 176c-5 15-5 36-1 55 3 14 11 22 15 16-2-21-4-46-4-65-2-7-7-10-10-6z"
        },
        {
          p: "M99 272c3 11 9 20 19 27v-27z"
        }
      ]
    },
    quads: {
      mirror: true,
      shapes: [
        {
          p: "M94 300c-10 5-15 20-15 37 0 21 5 41 11 54 4 8 11 6 11-4 0-23-2-58-4-77-1-8-2-11-3-10z"
        },
        {
          p: "M111 296c-6 2-8 15-8 33 0 22 2 44 6 57 3 8 8 7 8-2v-83c0-4-3-6-6-5z"
        },
        {
          p: "M116 352c-7 4-11 17-11 29 0 10 4 17 11 17z"
        }
      ]
    },
    calves: {
      mirror: true,
      shapes: [
        {
          p: "M110 402c-7 6-11 24-11 43 0 19 4 34 8 41 4 6 11 3 11-6v-73c0-5-4-7-8-5z"
        },
        {
          p: "M96 404c-8 9-11 27-10 45 1 14 6 21 9 14 2-18 2-42 1-56z"
        }
      ]
    }
  },
  back: {
    traps: {
      mirror: true,
      shapes: [
        {
          p: "M117 84c-13 2-25 8-34 19 11 9 23 15 34 17z"
        },
        {
          p: "M117 122c-11 2-21 10-27 22 7 19 15 40 21 56 3 7 6 6 6-2z"
        }
      ]
    },
    shoulders: {
      mirror: true,
      shapes: [
        {
          p: "M80 100c-14 8-22 26-22 46 0 11 7 15 15 8 8-6 14-22 16-38 1-10-3-18-9-16z"
        },
        {
          p: "M93 104c-8 7-13 19-13 31 0 8 6 10 11 4 6-7 9-21 8-30-1-6-4-8-6-5z"
        }
      ]
    },
    back: {
      mirror: true,
      shapes: [
        {
          p: "M113 150c-13 0-26 6-32 19-7 15-4 36 5 53 9 15 22 17 28 6 3-19 3-59-1-78z"
        },
        {
          p: "M104 138c-9 2-15 9-17 18 7 5 16 5 23 1 3-6 1-17-6-19z"
        }
      ]
    },
    triceps: {
      mirror: true,
      shapes: [
        {
          p: "M76 154c-11 7-18 26-20 46-1 13 5 21 13 14 9-8 13-30 15-49 0-9-4-14-8-11z"
        },
        {
          p: "M88 158c-5 13-8 30-8 43 5 0 9-7 10-18 2-13 1-24-2-25z"
        }
      ]
    },
    forearms: {
      mirror: true,
      shapes: [
        {
          p: "M62 214c-11 12-17 34-19 57-1 14 4 20 10 14 8-10 14-34 16-55 1-11-2-20-7-16z"
        },
        {
          p: "M74 224c-3 20-7 42-11 60 6 1 10-6 12-18 3-18 4-34 2-42z"
        }
      ]
    },
    core: {
      mirror: true,
      shapes: [
        {
          p: "M112 198c-7 7-10 24-8 43 2 15 8 24 14 20v-59c0-5-3-7-6-4z"
        }
      ]
    },
    glutes: {
      mirror: true,
      shapes: [
        {
          p: "M118 266c-13 0-26 7-32 20-7 15-2 32 11 39 11 5 21-1 21-13z"
        },
        {
          p: "M93 260c-9 5-14 16-12 27 7 0 14-7 16-16 1-7-1-13-4-11z"
        }
      ]
    },
    hamstrings: {
      mirror: true,
      shapes: [
        {
          p: "M99 326c-10 5-15 19-15 37 0 20 5 37 10 45 4 6 10 3 10-8 0-23-2-54-3-68-1-5-1-7-2-6z"
        },
        {
          p: "M116 326c-8 3-12 17-12 36 0 22 4 39 8 46 3 5 5 3 5-6v-70z"
        }
      ]
    },
    calves: {
      mirror: true,
      shapes: [
        {
          p: "M100 404c-10 7-15 26-14 46 1 15 6 24 12 19 3-19 3-47 2-64z"
        },
        {
          p: "M118 404c-9 5-14 23-13 43 1 15 5 24 11 20v-61z"
        },
        {
          p: "M108 458c-7 7-10 19-8 30 2 9 7 13 11 8 2-11 2-30 1-37z"
        }
      ]
    }
  }
};

export const SPLITS: Record<string, { primary: MuscleKey[]; secondary: MuscleKey[] }> = {
  "full-body": {
    primary: [
      "chest",
      "back",
      "quads",
      "shoulders",
      "core",
      "hamstrings",
      "glutes"
    ],
    secondary: [
      "biceps",
      "triceps",
      "calves",
      "traps",
      "forearms"
    ]
  },
  upper: {
    primary: [
      "chest",
      "back",
      "shoulders"
    ],
    secondary: [
      "biceps",
      "triceps",
      "traps",
      "core"
    ]
  },
  lower: {
    primary: [
      "quads",
      "hamstrings",
      "glutes"
    ],
    secondary: [
      "calves",
      "core"
    ]
  },
  push: {
    primary: [
      "chest",
      "shoulders",
      "triceps"
    ],
    secondary: [
      "core"
    ]
  },
  pull: {
    primary: [
      "back",
      "biceps"
    ],
    secondary: [
      "traps",
      "forearms",
      "shoulders"
    ]
  },
  legs: {
    primary: [
      "quads",
      "hamstrings",
      "glutes"
    ],
    secondary: [
      "calves"
    ]
  },
  arms: {
    primary: [
      "biceps",
      "triceps"
    ],
    secondary: [
      "forearms",
      "shoulders"
    ]
  },
  core: {
    primary: [
      "core"
    ],
    secondary: []
  }
};
